name: serialport-builder
on:
  push:
    branches:
      - master
jobs:
  build-serialport:
    name: Build serialport
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node: [15]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Linux dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install libudev-dev
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          cd node_modules/@serialport/bindings
          ../../.bin/node-gyp rebuild --target=12.0.4 --arch=x64 --dist-url=https://atom.io/download/electron
      - name: Upload
        run: node scripts/upload-bin.js --TYPE=serialport --REGION=${{ secrets.REGION }} --ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }} --ACCESS_KEY_SECRET=${{ secrets.ACCESS_KEY_SECRET }} --BUCKET=${{ secrets.BUCKET }}